### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by haesleinhuepf** [BioImage-Archive/bia-explorer#5]
Hi all, 

I just noticed that `bia-explorer` [on pypi](https://pypi.org/project/bia-explorer/) has version 0.1.1, while the version [here is 0.1.0](https://github.com/BioImage-Archive/bia-explorer/blob/31c0b730c9b1775383c143dec83c8fead514cb14/pyproject.toml#L3). Furthermore, it would be great if [github/git-tag releases](https://github.com/BioImage-Archive/bia-explorer/releases) were used for reproducible builds.

Thanks!

Best,
Robert

**Comment by liviuba** [comment]
Hi Robert,

Thanks for reporting this and the other issues! The options available for accessing BIA data have changed significantly since this repo was created, and we are now planning a more thorough revamp of bia-explorer and the example notebooks here.

We will definitely address all new issues in the update! Will let you know as the issues get fixed.

Kind regards,
Liviu

**Comment by haesleinhuepf** [comment]
Hi @liviuba ,

awesome, let me know if I can help! An accessible BioImage Archive could be key in my trainings ;-)

Best,
Robert

**Comment by liviuba** [comment]
Hi @haesleinhuepf ,

Thanks again for spotting this! We updated our tooling to ensure packages published on Pypi always match a tag.

Kind regards,
Liviu
